name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      plone:
        image: plone:4.3
        ports:
          - 8080:8080
        env:
          SITE: Plone
          PLONE_ADDONS: redturtle.exporter.base
          VERSIONS: redturtle.exporter.base=1.1.1

    strategy:
      max-parallel: 4
      matrix:
        python: ["3.7"]
        plone:
          ["52"]
          # exclude:
          #   - python: "3.7"
          #     plone: "51"
    steps:
      - uses: actions/checkout@v1
      - name: Cache eggs
        uses: actions/cache@v1
        with:
          path: eggs
          key: ${{ runner.OS }}-build-python${{ matrix.python }}-${{ matrix.plone }}
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt -c constraints_plone${{ matrix.plone }}.txt
          cp test_plone${{ matrix.plone }}.cfg buildout.cfg
      - name: Install buildout
        run: |
          buildout -N -t 3 code-analysis:return-status-codes=True
      - name: Run tests
        run: |
          bin/code-analysis
          bin/test
